# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceupp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 942)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.info_text = QtWidgets.QLabel(self.centralwidget)
        self.info_text.setGeometry(QtCore.QRect(0, 10, 691, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.info_text.setFont(font)
        self.info_text.setStyleSheet("QLabel{\n"
"    background-color: black;"
"color: white;"
"border: 3px solid white"
"\n"
"}")
        self.info_text.setText("")
        self.info_text.setObjectName("info_text")
        self.one_bt = QtWidgets.QPushButton(self.centralwidget)
        self.one_bt.setGeometry(QtCore.QRect(30, 130, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.one_bt.setFont(font)
        self.one_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.one_bt.setObjectName("one_bt")
        self.two_bt = QtWidgets.QPushButton(self.centralwidget)
        self.two_bt.setGeometry(QtCore.QRect(160, 130, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.two_bt.setFont(font)
        self.two_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.two_bt.setObjectName("two_bt")
        self.three_bt = QtWidgets.QPushButton(self.centralwidget)
        self.three_bt.setGeometry(QtCore.QRect(290, 130, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.three_bt.setFont(font)
        self.three_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.three_bt.setObjectName("three_bt")
        self.four_bt = QtWidgets.QPushButton(self.centralwidget)
        self.four_bt.setGeometry(QtCore.QRect(30, 260, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.four_bt.setFont(font)
        self.four_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.four_bt.setObjectName("four_bt")
        self.five_bt = QtWidgets.QPushButton(self.centralwidget)
        self.five_bt.setGeometry(QtCore.QRect(160, 260, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.five_bt.setFont(font)
        self.five_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.five_bt.setObjectName("five_bt")
        self.six_bt = QtWidgets.QPushButton(self.centralwidget)
        self.six_bt.setGeometry(QtCore.QRect(290, 260, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.six_bt.setFont(font)
        self.six_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.six_bt.setObjectName("six_bt")
        self.seven_bt = QtWidgets.QPushButton(self.centralwidget)
        self.seven_bt.setGeometry(QtCore.QRect(30, 390, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.seven_bt.setFont(font)
        self.seven_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.seven_bt.setObjectName("seven_bt")
        self.eight_bt = QtWidgets.QPushButton(self.centralwidget)
        self.eight_bt.setGeometry(QtCore.QRect(160, 390, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.eight_bt.setFont(font)
        self.eight_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.eight_bt.setObjectName("eight_bt")
        self.nine_bt = QtWidgets.QPushButton(self.centralwidget)
        self.nine_bt.setGeometry(QtCore.QRect(290, 390, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.nine_bt.setFont(font)
        self.nine_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.nine_bt.setObjectName("nine_bt")
        self.zero_bt = QtWidgets.QPushButton(self.centralwidget)
        self.zero_bt.setGeometry(QtCore.QRect(30, 520, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.zero_bt.setFont(font)
        self.zero_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.zero_bt.setObjectName("zero_bt")
        self.coma_bt = QtWidgets.QPushButton(self.centralwidget)
        self.coma_bt.setGeometry(QtCore.QRect(290, 520, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.coma_bt.setFont(font)
        self.coma_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.coma_bt.setObjectName("coma_bt")
        self.multiplication_bt = QtWidgets.QPushButton(self.centralwidget)
        self.multiplication_bt.setGeometry(QtCore.QRect(420, 520, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.multiplication_bt.setFont(font)
        self.multiplication_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.multiplication_bt.setObjectName("multiplication_bt")
        self.minus_bt = QtWidgets.QPushButton(self.centralwidget)
        self.minus_bt.setGeometry(QtCore.QRect(420, 390, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.minus_bt.setFont(font)
        self.minus_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.minus_bt.setObjectName("minus_bt")
        self.plus_bt = QtWidgets.QPushButton(self.centralwidget)
        self.plus_bt.setGeometry(QtCore.QRect(420, 260, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.plus_bt.setFont(font)
        self.plus_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.plus_bt.setObjectName("plus_bt")
        self.remove_bt = QtWidgets.QPushButton(self.centralwidget)
        self.remove_bt.setGeometry(QtCore.QRect(420, 130, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semiligh")
        font.setPointSize(28)
        self.remove_bt.setFont(font)
        self.remove_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.remove_bt.setObjectName("remove_bt")
        self.division_bt = QtWidgets.QPushButton(self.centralwidget)
        self.division_bt.setGeometry(QtCore.QRect(420, 650, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.division_bt.setFont(font)
        self.division_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.division_bt.setObjectName("division_bt")
        self.equals_bt = QtWidgets.QPushButton(self.centralwidget)
        self.equals_bt.setGeometry(QtCore.QRect(290, 650, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.equals_bt.setFont(font)
        self.equals_bt.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.equals_bt.setObjectName("equals_bt")
        self.white_theme = QtWidgets.QPushButton(self.centralwidget)
        self.white_theme.setGeometry(QtCore.QRect(270, 800, 171, 51))
        self.white_theme.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.white_theme.setObjectName("white_theme")
        self.black_theme = QtWidgets.QPushButton(self.centralwidget)
        self.black_theme.setGeometry(QtCore.QRect(50, 800, 181, 51))
        self.black_theme.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.black_theme.setObjectName("Black_theme")
        self.skob_open = QtWidgets.QPushButton(self.centralwidget)
        self.skob_open.setGeometry(QtCore.QRect(30, 650, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.skob_open.setFont(font)
        self.skob_open.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.skob_open.setObjectName("skob_open")
        self.skob_close = QtWidgets.QPushButton(self.centralwidget)
        self.skob_close.setGeometry(QtCore.QRect(160, 650, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.skob_close.setFont(font)
        self.skob_close.setStyleSheet("QPushButton  {\n"
"    background-color: orange;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"\n"
"\n"
"\n"
"}")
        self.skob_close.setObjectName("skob_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.one_bt.setText(_translate("MainWindow", "1"))
        self.two_bt.setText(_translate("MainWindow", "2"))
        self.three_bt.setText(_translate("MainWindow", "3"))
        self.four_bt.setText(_translate("MainWindow", "4"))
        self.five_bt.setText(_translate("MainWindow", "5"))
        self.six_bt.setText(_translate("MainWindow", "6"))
        self.seven_bt.setText(_translate("MainWindow", "7"))
        self.eight_bt.setText(_translate("MainWindow", "8"))
        self.nine_bt.setText(_translate("MainWindow", "9"))
        self.zero_bt.setText(_translate("MainWindow", "0"))
        self.coma_bt.setText(_translate("MainWindow", ","))
        self.multiplication_bt.setText(_translate("MainWindow", "*"))
        self.minus_bt.setText(_translate("MainWindow", "-"))
        self.plus_bt.setText(_translate("MainWindow", "+"))
        self.remove_bt.setText(_translate("MainWindow", "C"))
        self.division_bt.setText(_translate("MainWindow", "/"))
        self.equals_bt.setText(_translate("MainWindow", "="))
        self.white_theme.setText(_translate("MainWindow", "White theme"))
        self.black_theme.setText(_translate("MainWindow", "Black theme"))
        self.skob_open.setText(_translate("MainWindow", "("))
        self.skob_close.setText(_translate("MainWindow", ")"))
